### ISSUE TITLE
Feature request: Reference implementation for using stripe.proxy to stripe-mock

### ISSUE THREAD

**Issue by bowlofstew** [stripe/stripe-python#615]
I am attempting to leverage the [stripe-mock](https://github.com/stripe/stripe-mock) library against an application that I am working on that consumes the stripe-python library.  I am attempting to create an docker-compose implementation that allows for local developers to leverage the stripe-mock component in a docker container spun up from the compose manifest.  As part of this I am leveraging the [stripe.proxy](https://sourcegraph.com/github.com/stripe/stripe-python/-/blob/examples/proxy.py) component.  When doing such, I am getting a message of 

```
our container: message='Request to Stripe api' method=get path=https://api.stripe.com/v1/plans?limit=100
our_container: api_version=None message='Post details' post_data=limit=100
stripe mock container    | 2019/09/13 15:22:13 http: TLS handshake error from 172.18.0.3:60840: tls: oversized record received with length 20037```
```

The changes introduced to the code looks as follows:

```
stripe.log = "debug"
stripe.proxy = {"http": "http://stripe:12111", "https": "https://stripe:12112"}
```
This from my read of the example [here]() appears to be sufficient to both proxy and log the proxy of request and response pairs.  

The docker implementation looks as follows:

```
version: "3.7"

services:
  base:
    image: mozilla/subhub-base
    container_name: base
    build:
      context: .
      dockerfile: Dockerfile.base
  sub:
    container_name: sub
    image: mozilla/sub
    command: python3 sub/app.py
    build:
      context: src/sub
      dockerfile: Dockerfile
      args:
        LOCAL_FLASK_PORT: 5000
        DYNALITE_PORT: 4567
    environment:
        AWS_ACCESS_KEY_ID: "fake-id"
        AWS_SECRET_ACCESS_KEY: "fake-key"
        STRIPE_API_KEY: $STRIPE_API_KEY
        SUPPORT_API_KEY: $SUPPORT_API_KEY
        PAYMENT_API_KEY: $PAYMENT_API_KEY
        SUPPORT_API_KEY: $SUPPORT_API_KEY
    ports:
      - "5000:5000"
    depends_on:
      - base
      - dynalite

  hub:
    container_name: hub
    image: mozilla/hub
    command: python3 hub/app.py
    build:
      context: src/hub
      dockerfile: Dockerfile
      args:
        LOCAL_FLASK_PORT: 5001
        DYNALITE_PORT: 4567
    environment:
        AWS_ACCESS_KEY_ID: "fake-id"
        AWS_SECRET_ACCESS_KEY: "fake-key"
        STRIPE_API_KEY: $STRIPE_API_KEY
        HUB_API_KEY: $HUB_API_KEY
    ports:
      - "5001:5001"
    depends_on:
      - base
      - dynalite

  dynalite:
    build: https://github.com/vitarn/docker-dynalite.git
    ports:
      - 4567

  stripe:
    image: stripemock/stripe-mock:latest
    ports:
      - "12111:12111"
      - "12112:12112"
```

Do you have any reference documentation around this use case or best practices available?  I have tried several different incantations of the `stripe.proxy` setting as well to that affect.

The entire codebase itself with those changes are available [here](https://github.com/mozilla/subhub/compare/feature/stripe-mock?expand=1) should you want to see the approach.
